apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: idp-portal
  title: IDP Portal
  description: Backstage-based developer portal for the Internal Developer Platform Demo.
spec:
  type: website
  lifecycle: experimental
  owner: platform-team
